from datetime import datetime, date, timedelta
from time import sleep
import numpy as np
#from tarfile import TruncatedHeaderError

def using_sleep():
    sleep(5)

def using_dates():
    first_of_month = date(2025, 11, 1)
    last_of_month = date(2025, 12, 31) - timedelta(days=1)

def using_timestamps():
    start_ts = datetime.now()
    end_ts = datetime.now()
    print("This operation took: ", end_ts - start_ts, "seconds.")

def factorial_recursive(n):
    if n == 0:
        return 1
    return n * factorial_recursive(n - 1)

def using_functions_as_attributes():
    def say_hello():
        print("Hello World!")

    def do_twice(f):
        f()
        f()

    #Example
    do_twice(say_hello) #say_hello is a name of a function. Add () to it, and the normal name becomes a function, that is then executed.

    def repeated_call(func, number, *args, **kwargs):
        for i in range(number):
            func(*args, **kwargs)

    def hello_world(name: str):
        print(f"Hello {name}!")

    #Example
    repeated_call(hello_world, 3, name="Yves")

def verify_e_id(eid:int):
    first_9 = eid // 100
    last_2 = eid % 100
    """
    >> > verify_e_id(595084551177)
    2.5
    """
    return first_9 % 97 == last_2

def eid_verification(eid: str) -> bool: #Generated by ChatGPT
    """
    Validate a Belgian National Register number (11 digits + optional separators).
    Format: YYMMDDXXXCC
    """

    # Remove common separators (., -, space)
    cleaned = ''.join(ch for ch in eid if ch.isdigit())

    if len(cleaned) != 11:
        return False

    first9 = cleaned[:9]
    checksum = int(cleaned[9:11])

    # Birth year indicator: determines if "2" prefix is used for post-2000 births
    # Try pre-2000 formula
    try_pre2000 = 97 - (int(first9) % 97)
    if try_pre2000 == checksum:
        return True

    # Try post-2000 formula
    try_post2000 = 97 - (int("2" + first9) % 97)
    if try_post2000 == checksum:
        return True

    return False


    # Example usage:
    samples = [
        "97.07.15-123.61",   # valid example (born 1997)
        "03.01.20-456.82",   # valid example (born 2003)
        "99010112345",       # invalid
    ]

    for s in samples:
        print(f"{s}: {'VALID' if eid_verification(s) else 'INVALID'}")

def docstring_numpy_style():
    #import numpy as np

    def calculate_mean(data):
        """
        Calculate the mean of a numeric array.

        Parameters
        ----------
        data : array_like
            An array of numeric values.

        Returns
        -------
        float
            The mean value of the array.

        Examples
        --------
        >>> calculate_mean([1, 2, 3, 4])
        2.5
        """
        return np.mean(data)

    print(calculate_mean.__doc__)

KILOMETERS_TO_MILE = 1.61
def calculating_with_miles_kilometers():
    minutes = 42
    seconds = 42

    total_seconds = minutes * 60 + seconds
    print(total_seconds)

    #Global variable
    # KILOMETERS_TO_MILE = 1.61

    kms = 10
    miles = KILOMETERS_TO_MILE * kms
    print(kms, "km is gelijk aan", miles, "mijlen")

    distance_km = 10
    minutes = 42
    seconds = 42
    total_seconds = minutes * 60 + seconds
    distance_miles = distance_km / KILOMETERS_TO_MILE
    print("distance mijlen", distance_miles)

    pace = total_seconds / distance_miles
    print(pace)

    pace = round(pace, 3)

    pace_minutes = pace // 60
    print(pace_minutes)
    pace_seconds = pace % 60
    print(pace_seconds)

    pace = 1 / pace * 60 * 60
    print(pace)

def convert_kilometers_to_miles(kilometers: float) -> float:
    return kilometers / KILOMETERS_TO_MILE

def convert_miles_to_kilometers(miles: float) -> float:
    return miles * KILOMETERS_TO_MILE

#Chapter 7
def uses_any(word, letters):
    for letter in word():
        if letter in letters:
            return True

    return False

def uses_none(word, letters):
    for letter in letters:
        if letter in word:
            return False

    return True

def uses_only(word, letters):
    for w in word:
        if w not in letters:
            return False

    return True

def uses_all(word, letters):
    for letter in letters:
        if letter not in word:
            return False

    return True

def check_word(word, letters, required = None):
    if required is not None:
        assert required in letters, "required must be in letters"

    if len(word) < 4:
        return False


    if required is not None and required not in word:
        return False

    return uses_any(word, letters)

def word_score(word: str, letters: str):
    for w in word:
        if w not in letters:
            return 0

    extra_points = 7

    for letter in letters:
        if letter not in word:
            extra_points = 0
            break

    if len(word) == 4:
        return 1
    else:
        return len(word) + extra_points

def uses_all_reverse_attributes(word, letters):
    return uses_only(letters, word)

#ex_strings
def is_palindrome(word: str) -> bool:
    return word.lower() == word[::-1].lower()

def is_palindrome_alt(word: str) -> bool:
    word = word.lower()

    return  word == word[::-1]

def is_voodoo(word: str) -> bool:
    return is_palindrome(word[1:])

def is_voodoo_alt(word: str) -> bool:
    word = word.lower()

    moved = word[1:] + word[0]

    return word[::-1] == moved

def is_anagram(word1: str, word2: str) -> bool:
    return sorted(word1.lower()) == sorted(word2.lower())

def is_in_words_alt(word: str) -> bool:
    with open("words.txt") as f:
        lines = f.readlines()

        for w in lines:
            if word == w.strip():
                return True

    return False

def is_in_words(word: str) -> bool:
    with open("words.txt") as f:
        words = f.read().split("\n")

        return word in words

def is_existing_anagram_alt(word1: str, word2: str) -> bool:
    if not(is_anagram(word1, word2)):
        return False

    return is_in_words(word1) and is_in_words(word2)

def is_existing_anagram(word1: str, word2: str) -> bool:
    if not(is_anagram(word1, word2)):
        return False

    with open("words.txt") as f:
        words = f.read().split("\n")

        return word1 in words and word2 in words

def is_existing_anagram_b(word1: str, word2: str) -> bool:
    if not(is_existing_anagram(word1, word2)):
        return False

    with open("words.txt") as f:
        words = f.read()
        words = f"\n{words}\n"

        return f"\n{word1}\n" in words and f"\n{word2}\n" in words

def is_real_anagram(word: str) -> bool:
    with open("words.txt") as f:
        words = f.read().split("\n")

        found = False
        anagram = False

        for w in words:
            if w == word:
                found = True
            elif is_anagram(w, word):
                anagram = True

            if anagram and found:
                return True

        return False

""" def most_vowels() -> str: """
# def most_vowels() -> str:
#     with open("words.txt") as f:
#         return sorted([{word:sum(1 for char in word if char in "aeiou")} for word in f.read().split("\n") if len(word) > 0], key=lambda d: list(d.values())[0])[-1]

def longest_palindrome() -> str:
    length = -1
    longest = ""

    with open("words.txt") as f:
        words = f.read().split("\n")

        for w in words:
            if len(w) > length and is_palindrome(w):
                length = len(w)
                longest = w

    return longest

#Globals always in upper case

def explained_arithmetic_functions():
    # import sys
    # import debug
    # sys.exit(0)       #sys can only be used in main() and closes the program

    # Benamingen die mogen, maar niet in formele code
    me = "Brent Hendricx"
    you = 'Yves Vindevogel'

    # Benamingen liever nooit gebruiken
    een = 1  # Naam mogelijk, niet aangeraden
    tweeeneenhalf = 2.5  # Decimal point als punt
    toto = 2, 5  # Decimal point als komma

    print("hello", "world", me, sep="-", end="")

    # types van waardes in variabelen
    print(type(me))  # Bij run = Geeft <class 'str'>
    print(type(you))  # Bij run = Geeft <class 'str'>
    print(type(een))  # Bij run = Geeft <class 'int'>
    print(type(tweeeneenhalf))  # Bij run = Geeft <class 'float'>

    # ChatGPT geeft dit als antwoord om de antwoorden hierboven te krijgen
    print(isinstance(me, str))
    print(isinstance(een, int))
    # Verschil bij type en isinstance: type is in het algemeen gebruikbaar voor het opvragen van het type van een variabel (Maurice is een kat, is geen beest)
    #                                 isinstance let op het overerven als je vraagt of "Maurice" een type beest is. (Maurice is een kat, is een beest)

    # Getallen en type
    a = 1  # int
    b = 2  # int
    c = a + b  # int
    d = 2.5  # float
    e = c + d  # float
    print(e)
    print(type(e))

    print(2 + 2.0)  # type is 4.0 en dus een float

    print(1 - 2)  # int
    print(2 * 7)  # int
    print(4 ** 2)  # int Math.Pow(4,2), Macht tot de 2de
    print(4 / 2)  # geeft altijd een float omdat het "delen" is. Geen "if" om te checken, het moet gwn snel gaan.
    print(2 / 3)  # oneindige getallen achter decimal is 16 na de komma
    print(4 // 3)  # resultaat 1    intiger deling (rest wegdoet)   6//4 is 1 met rest 2
    print(-4 // 3)  # resultaat -2  Rondt af naar beneden, niet naar nul. Uitkomst is -1.33333 afgerond is dus -2
    print(7 % 2)  # resultaat 1        modulo = geeft de rest van een deling

    print(7 ^ 2)  # binaire rekensom (5)
    print(6 ^ 3)  # binaire rekensom (2)
    print(6 >> 2)  # binaire rekensom (1)
    print(6 >> 1)  # binaire rekensom (3)

    # lang binair nummer snel omrekenen (enkel bij positieve gehele getallen)
    # 110110110 = 438
    # startend bij het eerste 1-tje (volgende binair is 1? doe maal 2 plus 1) (volgende binair is 0, doe maal 2)
    # 1 1
    # 1 (* 2 + 1)   3
    # 0 (* 2)       6
    # 1 (* 2 + 1)   13
    # 1 (* 2 + 1)   27
    # 0 (* 2)       54
    # 1 (* 2 + 1)   109
    # 1 (* 2 + 1)   219
    # 0 (* 2)       438

    file = "C:\\Users\\Brent\\Desktop\\Python\\Syntra\\hello.py"
    # Een \ in text, is voor het volgende speciale teken gewoon te maken (schrijft de \ dan ook niet)

    a = 1
    a = "Yves"
    b = "Toto"

    # a=1
    # print(a) #1
    a = "Brent"
    print(a)  # Brent
    b = "Hendricx"
    print(a + b)  # Brent Hendricx
    # print(a-b) #ERROR, strings kunnen niet bij afgetrokken worden
    print(" " * 30)  # 30 spaties
    print("              ")  # NOOIT zo doen

    x = 1
    y = "test"
    # print(x+y) #Geeft fout, int en string kunnen niet bij elkaar worden getelt

    punten = 90
    totaal = 100
    result = punten / totaal * 100
    print("U behaalde " + str(result) + " punten")
    print("U behaalde", result, "punten")
    print(f"U behaalde {result} punten")

    s = """
    sqfs
    fdsqf
    dsqfdsq
    fds
    q
    """

    #
    # i = input("Geef een getal:")
    # print("U behaalde" + str(int(i)  / 100) + "percent")

    print(len("Yves"))  # len = Length van de string (met spaties), resultaat = 5

    # Naam voor versies v#(1).#(2).#(3) bv. v2.14.3
    # (1) Veranderen in "version breaking updates" (nieuwe functies die oude functies breken)
    # (2) Veranderen in "functionality updates" (nieuwe functionaliteiten zonder code te breken)
    # (3) Veranderen in "bugfixes" (code aanpassen dat niet breekt zoals een foutje corrigeren)

def using_loops(x: int, y: int) -> int:
    if y == 0:
        return 0

    while True:
        x += 1

        if x > 5:
            break

    for letter in "Hendricx":
        if letter == "i":
            continue

        print(letter)

    return 0

#one-liners
def triangle(char: str, size: int):
    for i in range(size):
        print(char * (i + 1))

def oneline_grid(box_width, amount_width, box_height, amount_height):
    print((((" ".join(" " for i in range(box_width + 1))).join(
        "|" for i in range(amount_width + 1)) + "\n") * box_height).join(
        (("-".join(" " for i in range(box_width + 1))).join("+" for i in range(amount_width + 1)) + "\n") for i in
        range(amount_height + 1)))

def is_prime(n):
    """

    :param n: int
    :return: True if n is prime, False otherwise
    """
    assert type(n) is int
    assert n > 0

    if n == 1:
        return False

    if n % 2 == 0:
        return False

    for i in range(3, n ** 0.5 + 1, 2):
        if n % i == 0:
            return False

    return True

def using_open_documents():
    #pycharm generated
    with open("words.txt") as f:
        words = f.read().split("\n")

    for line in open("words.txt", "r"): # r = example for reading, w example for writing
        print(line)

def recursive_fibo(n):
    def go(n, a, b):
        while n > 0:
            c = a
            a = b
            b = c + a
            n = n - 1

        return a

    return go(n, 0, 1)

def ways_to_switch_variable_values():
    a = 2
    b = 3

    # c = b
    # b = a
    # a = c

    # a = a + b
    # b = a - b
    # a = a - b

    # a = a ^ b
    # b = b ^ a
    # a = a ^ b

    a, b = b, a

    assert a == 3
    assert b == 2

""" Tricky Import
from ex7 import required

from globals import APPLICATION_NAME
"""







def main():
    print("Printed from main()")
    assert convert_kilometers_to_miles(1) == 1 / KILOMETERS_TO_MILE
    assert convert_miles_to_kilometers(1) == 1.61

    print(word_score("card", "acdlort"))
    print(word_score("color", "acdlort"))
    print(word_score("cartload", "acdlort"))

    assert is_voodoo("yves") == False
    # print(most_vowels())

    #one-liners
    triangle(char="*", size=5)
    # print( "\n".join(["*" * (i + 1) for i in range(5)]))
    oneline_grid(box_width=4, amount_width=5, box_height=5, amount_height=2)
    #HIER PROGRAMMEREN

if __name__ == "__main__":
    main()